### ISSUE TITLE
how to customize ?

### ISSUE THREAD

**Issue by nitneuq33000** [apptreesoftware/flutter_google_map_view#48]
hello there is way to customize the toolbar in map_view? or add widgets (floatingactionbutton). 

example : 
![image](https://user-images.githubusercontent.com/38652337/40413352-eb50b4b0-5e75-11e8-8b8c-d7039675fbba.png)

currently map_view opens a new window full screen with a slide to the left with a black toolbar. I would like to customize the page transistion , color toolbar and add widgets to interact without having to go back.

Finally, it would not be possible to have the dynamic map in a pop up box instead of a full screen, or in a card ?

thank you

**Comment by andreagr** [comment]
That would really be nice.
Also adding custom markers would be a very useful feature.
I guess these enhancement could be added quite easily adding some fields to the proper pages. We could try to propose some additions to the code.

**Comment by johnpryan** [comment]
If you want an in-line map or custom widgets overlaying the map, consider using https://github.com/apptreesoftware/flutter_map instead. If that doesn't work for your use-case, let us know- we are always looking for feedback!

**Comment by andreagr** [comment]
Would it be suitable for a production app? I can see there would be the need to choose between different tile providers.
Having to pay for a good one there doesn't appeal a lot to me...I forked, I will try to see if I can integrate some functions, and in case I will show it to you, so you can consider pulling it

**Comment by ericam92** [comment]
custom markers and a little customization of the toolbar would be a great addition to this widget. I'm glad to see other users think the same

**Comment by bstuddard** [comment]
I wonder how hard it would be to modify the marker title to accept html strings (maybe as a parameter that is basic text but an optional parameter could signify that it is supposed to render html) .

That would allow some level of customization beyond a simple string title. I imagine it would be changing the text view rendering on the marker info box to something like the following.

if (methodType.equals("html")){
textView.setText(Html.fromHtml(userFlutterPassedString));
} else
{
textView.setText(userFlutterPassedString);
} 

The new methodType parameter could default to plain text but allow the plugin user to specify if they are passing in html. 

Would alow for a lot of interesting uses on what to display when a user clicks on a marker. Thoughts?

**Comment by bstuddard** [comment]
I'm not experienced in Kotlin, so I'll just throw this idea out there to see what everyone thinks. What if a custom info window was implemented? I did some digging and found that the customization likely has to do with configurations of the google libraries. 

For example, a custom InfoWindowAdapter could be implemented and then in the onMapReady overridden function in the MapActivity.kt file, a call could be made to set the GoogleMap object with a custom InfoWindowAdapter as such GoogleMap.setInfoWindowAdapter(). The custom window adaptor could be as simple as rendering a textview that takes a HTML string. This would allow flexibility on behalf of the Flutter developer to pass in a more customized text rather than a simple string. 

Thoughts? 

https://developers.google.com/maps/documentation/android-sdk/infowindows

**Comment by bstuddard** [comment]
FYI, I added a pull request associated with the above comment.

**Comment by andreagr** [comment]
This seems really interesting! @bstuddard hope it can get implemented into the library officially, also with iOS support. Thanks a lot for you contribution!

**Comment by nitneuq33000** [comment]
@bstuddard thanks for your contribution ! 
Currently the major problem for my app is the color of the appbar of map_view  in full screen. No way to easily custom color appbar ?

**Comment by andreagr** [comment]
I have been looking at the plugin suggested by jhonpryan above. I have to say that it actually answers to many of the issues presented here. It's more customizable and I might say even kinda easier to use.
The only problem is that it doesn't support google maps, so that might be an issue, even though i think adding a couple of things could be just perfect. #

**Comment by matthewtsmith** [comment]
We have no plans to support further customization in this library unless the community wants to contribute it. All of our dev focus is on the library that @johnpryan mentioned: https://github.com/apptreesoftware/flutter_map
